package com.partsystem.partvisitapp.core.network.modelDto

data class PatternDto(
    val id: Int,
    val code: Int,
    val name: String,
    val createDate: String?,
    val persianDate: String?,
    val fromDate: String?,
    val fromPersianDate: String?,
    val toDate: String?,
    val toPersianDate: String?,
    val arzId: Int?,
    val description: String?,
    val settelmentKind: Int?,
    val creditDuration: Int?,
    val discountInclusionKind: Int?,
    val groupInclusionKind: Int?,
    val centerInclusionKind: Int?,
    val customerInclusionKind: Int?,
    val processInclusionKind: Int?,
    val regionInclusionKind: Int?,
    val sabt: Boolean,
    val fromSaleAmount: Double?,
    val toSaleAmount: Double?,
    val hasCash: Boolean,
    val hasMaturityCash: Boolean,
    val hasSanad: Boolean,
    val hasSanadAndCash: Boolean,
    val hasCredit: Boolean,
    val dayCount: Int?,
    val hasAndroid: Boolean,
    val patternDetails: List<Any>?
)
