package com.partsystem.partvisitapp.core.network.modelDto

data class ProductDto(
    val id: Int,
    val code: String,
    val name: String,
    val kind: Int,
    val groupProductId: Int?,
    val groupProductDetailId: Int?,
    val rastehId: Int?,
    val unitId: Int?,
    val unit2Id: Int?,
    val technicalNumber: String,
    val excludeVat: Boolean,
    val vatPercent: Double,
    val excludeToll: Boolean,
    val tollPercent: Double,
    val productSerial: Boolean,
    val description: String,
    val productKindId: Int?,
    val impureWeight: Double,
    val pureWeight: Double,
    val unitCode: Int?,
    val unitName: String?,
    val unit2Code: Int?,
    val unit2Name: String?,
    val sabt: Boolean,
    val isSalable: Boolean,
    val saleName: String?,
    val saleGroupId: Int?,
    val saleGroupDetailId: Int?,
    val saleRastehId: Int?,
)
