package com.partsystem.partvisitapp.core.network.modelDto

data class ReportFactorDto(
    val id: Int,
    val code: Int,
    val mainCode: Int,
    val persianDate: String,
    val createTime: String,
    val invoiceCategoryCode: Int,
    val invoiceCategoryName: String,
    val customerCode: Long,
    val customerName: String,
    val patternCode: Int,
    val patternName: String,
    val sumPrice: Double,
    val sumDiscountPrice: Double,
    val sumVat: Double,
    val finalPrice: Double,
    val anbarCode: Int?,
    val anbarName: String?,
    val productCode: Int?,
    val productName: String?,
    val unitCode: Int?,
    val unitName: String?,
    val unit1Value: Double?,
    val unit2Value: Double?,
    val packingValue: Double?,
    val packingCode: Int?,
    val packingName: String?,
    val discountPrice: Double?,
    val price: Double?,
    val priceAfterDiscount: Double?,
    val vat: Double?,
    val rate1: Double?,
    val priceAfterVat: Double?
)
