package com.partsystem.partvisitapp.feature.main.home.model

data class DiscountDto(
    val id: Int,
    val formType: Int,
    val code: Int,
    val name: String,
    val kind: Int,
    val isAutoCalculate: Boolean,
    val applyKind: Int,
    val calculationKind: Int,
    val inclusionKind: Int,
    val paymentKind: Int,
    val priceAmount: Double,
    val priceKind: Int,
    val sabt: Boolean,
    val beginDate: String,
    val persianBeginDate: String,
    val hasCash: Boolean,
    val hasMaturityCash: Boolean,
    val hasSanad: Boolean,
    val hasSanadAndCash: Boolean,
    val hasCredit: Boolean,
    val dayCount: Int,
    val isSystem: Boolean,
    val hasUseToolsPercnet: Boolean,
    val hasUseToolsPrice: Boolean,
    val unitKind: Int?,
    val hasLastControl: Boolean,
    val executeKind: Int,
    val maxPrice: Double,
    val customerFilterKind: Int,
    val toDate: String?,
    val toPersianDate: String?,
    val discountEshantyuns: List<DiscountEshantyunsDto>?,
    val discountGifts: List<DiscountGiftsDto>?,
    val discountGroups: List<DiscountGroupsDto>?,
    val discountProductKindInclusions: List<DiscountProductKindInclusionsDto>?,
    val discountProductKinds: List<DiscountProductKindsDto>?,
    val discountProducts: List<DiscountProductsDto>?,
    val discountStairs: List<DiscountStairsDto>?,
    val discountUsers: List<DiscountUsersDto>?,
    val discountCustomers: List<DiscountCustomersDto>?,
    )


