package com.partsystem.partvisitapp.feature.create_order.model

data class ValidateCredit(
    val creditMainCode: Int,
    val kind: Int,
    val kindDescription: String,
    val mandeh: Double,
    val hasWarningOrder: Boolean,
    val hasWarningFactor: Boolean,
    val hasErrorOrder: Boolean,
    val hasErrorFactor: Boolean,
    val accountRemain: Double,
    val asnadRemain: Double,
    val totalRemain: Double,
    val maxValidAsnad: Double,
    val maxFactor: Int,
    val maxFactorYear: Int,
    val maxSalePrice: Double,
    val maxSalePriceYear: Double,
    val maxBackFactor: Int,
    val maxBackFactorYear: Int,
    val maxSaleYear: Double,
    val maxSale: Double,
    val factorCountYear: Int,
    val backFactorCountYear: Int,
    val factorCount: Int,
    val backFactorCount: Int,
    val hasWarningDistribution: Boolean,
    val hasErrorDistribution: Boolean
)
